[phases.setup]
nixPkgs = ["python311", "libpq"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "flask --app wsgi.py db upgrade && python seed.py && gunicorn wsgi:app --bind 0.0.0.0:$PORT"