"""needs attention field

Revision ID: 01c8303356cc
Revises: 8d0bf335d7bb
Create Date: 2026-06-03 16:47:30.258209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c8303356cc'
down_revision = '8d0bf335d7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('conversation_modes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_attention', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_modes', schema=None) as batch_op:
        batch_op.drop_column('needs_attention')

    op.drop_table('push_tokens')
    # ### end Alembic commands ###
