"""add conversation_modes table

Revision ID: 8228ce2211b3
Revises: cc0eda3178e7
Create Date: 2026-06-01 21:40:28.119421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8228ce2211b3'
down_revision = 'cc0eda3178e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_modes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_modes_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_modes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_modes_phone'))

    op.drop_table('conversation_modes')
    # ### end Alembic commands ###
