"""conversation history and state

Revision ID: 8d0bf335d7bb
Revises: 8228ce2211b3
Create Date: 2026-06-03 16:38:19.816571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0bf335d7bb'
down_revision = '8228ce2211b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_history_phone'), ['phone'], unique=False)

    op.create_table('conversation_state',
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('selected_service_id', sa.Integer(), nullable=True),
    sa.Column('selected_service_name', sa.String(length=200), nullable=True),
    sa.Column('selected_service_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('selected_service_duration', sa.Integer(), nullable=True),
    sa.Column('selected_category', sa.String(length=50), nullable=True),
    sa.Column('pending_date', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_state')
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_history_phone'))

    op.drop_table('conversation_history')
    # ### end Alembic commands ###
