"""add promotion and discount to appointments

Revision ID: cc0eda3178e7
Revises: e5ea60017111
Create Date: 2026-05-13 21:01:54.856632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0eda3178e7'
down_revision = 'e5ea60017111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key(None, 'promotions', ['promotion_id'], ['id'])

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_uses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_uses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_column('current_uses')
        batch_op.drop_column('max_uses')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('final_price')
        batch_op.drop_column('discount_applied')
        batch_op.drop_column('promotion_id')

    # ### end Alembic commands ###
